import config from '../config/config';

export const GENESIS_TRANSACTION_MAIN_NETWORK = '2VngVznbdiQ5tqfWqn2NMP8DijqCbLX79Gygo9yYRVFU6iN35h';
export const GENESIS_TRANSACTION_TEST_NETWORK = 'wFtfcYFJb75bJCGU3HVsPCRg8RDHnMmsRL565BSaeu3aidqQN';
export const GENESIS_SHARD_ID_MAIN_NETWORK    = 'qGuUgMMVmaCvqrvoWG6zARjkrujGMpzJmpNhBgz1y3RjBG7ZR';
export const GENESIS_SHARD_ID_TEST_NETWORK    = '2qkemPc9SozT4r8TdcMgyv9DxgE8m4qUkEJ2eBRQLCNP9GD4Vh';
export default {
    genesis_transaction: config.MODE_TEST_NETWORK ? GENESIS_TRANSACTION_TEST_NETWORK : GENESIS_TRANSACTION_MAIN_NETWORK,
    genesis_shard_id   : config.MODE_TEST_NETWORK ? GENESIS_SHARD_ID_TEST_NETWORK : GENESIS_SHARD_ID_MAIN_NETWORK
};
